web:
  build: .
  restart: always
  expose:
    - "80"
  links:
    - postgres
  env_file:
    - ./env/django.env
  environment:
    # the following vars need to be overridden because the directive env_file
    # does not compute their value from the other variables
    - DATABASE_URL=${DATABASE_URL}
  command: gunicorn --reload -w 4 -b :80 --chdir /usr/src/app/src wsgi:application

postgres:
  image: postgres:10
